<?php

namespace Scourgen\PersonFinderBundle\Repository;

/**
 * PersonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonRepository extends \Doctrine\ORM\EntityRepository
{
    public function findPersonByName($full_name){
        $qb=$this->getEntityManager()
            ->createQueryBuilder()
            ->select('p')
            ->from('ScourgenPersonFinderBundle:Person','p')
            ->where('p.fullName like :full_name')
            ->setParameter('full_name','%'.$full_name.'%');
        return $qb->getQuery()->getResult();
    }
}
